export type CleaningSolution = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  image: string;
  serviceSlug: string;
  problem: string;
  whyItMatters: string;
  bestPlan: string;
  bullets: string[];
  faqs: {
    q: string;
    a: string;
    links?: { label: string; href: string }[];
  }[];
};

const baseFaq = (serviceSlug: string) => [
  {
    q: "Can I get a quote on WhatsApp?",
    a: "Yes. Send your location, photos, property type, preferred timing, and the issue you want solved. Photos make the quote clearer and reduce back-and-forth.",
    links: [{ label: "Contact", href: "/contact" }],
  },
  {
    q: "Which service should I choose?",
    a: "Choose the service that matches the problem. If you are unsure, send photos and Just Shine Cleaning Services can guide you before booking.",
    links: [{ label: "Related service", href: `/services/${serviceSlug}` }],
  },
];

export const cleaningSolutions: CleaningSolution[] = [
  {
    slug: "dust-control-cleaning-abu-dhabi",
    title: "Dust Control Cleaning in Abu Dhabi",
    eyebrow: "Dust solution",
    description: "A practical cleaning plan for Abu Dhabi homes where desert dust returns quickly on floors, shelves, windowsills, and AC-exposed surfaces.",
    image: "/images/services/home-cleaning.webp",
    serviceSlug: "home-cleaning",
    problem: "Fine dust settles on visible surfaces within days, especially in apartments with AC airflow, balcony access, and frequent window or door use.",
    whyItMatters: "Dust affects comfort, allergies, furniture appearance, and how quickly a home feels unclean after a normal tidy-up.",
    bestPlan: "Weekly or bi-weekly home cleaning with periodic deep cleaning for corners, vents, frames, and hidden buildup.",
    bullets: ["Wipe high-use surfaces and shelves.", "Vacuum and mop floors regularly.", "Add deep cleaning when corners and frames hold buildup."],
    faqs: baseFaq("home-cleaning"),
  },
  {
    slug: "allergy-friendly-cleaning-abu-dhabi",
    title: "Allergy-Friendly Cleaning in Abu Dhabi",
    eyebrow: "Allergy support",
    description: "Cleaning guidance for homes where dust, pet dander, fabric buildup, and AC circulation can trigger allergy symptoms.",
    image: "/images/services/deep-cleaning.webp",
    serviceSlug: "deep-cleaning",
    problem: "Allergens can collect in fabrics, carpets, corners, vents, bedding areas, curtains, sofas, and high-dust rooms.",
    whyItMatters: "A cleaner environment can help reduce dust exposure and make bedrooms, living rooms, and family spaces feel fresher.",
    bestPlan: "Combine regular home cleaning with deep cleaning, sofa cleaning, carpet cleaning, and focused bedroom dust removal when needed.",
    bullets: ["Prioritize bedrooms and living rooms.", "Clean fabrics and carpets separately if needed.", "Use recurring cleaning to reduce buildup."],
    faqs: baseFaq("deep-cleaning"),
  },
  {
    slug: "pet-odor-cleaning-abu-dhabi",
    title: "Pet Odor Cleaning in Abu Dhabi",
    eyebrow: "Pet homes",
    description: "Cleaning support for homes with pet hair, odor, dander, sofa marks, carpet spots, and high-use pet areas.",
    image: "/images/services/sofa-cleaning.webp",
    serviceSlug: "sofa-cleaning",
    problem: "Pet odors and hair often settle into sofas, rugs, carpets, corners, and areas where pets sleep or eat.",
    whyItMatters: "Pet odors can return if only visible surfaces are cleaned and fabric areas are ignored.",
    bestPlan: "Start with home cleaning, then add sofa or carpet cleaning for fabric areas that hold odor or stains.",
    bullets: ["Send photos of fabric stains.", "Mention pets before booking.", "Allow drying time after fabric cleaning."],
    faqs: baseFaq("sofa-cleaning"),
  },
  {
    slug: "carpet-stain-removal-abu-dhabi",
    title: "Carpet Stain Removal Cleaning in Abu Dhabi",
    eyebrow: "Stain support",
    description: "A carpet cleaning solution page for food stains, traffic marks, drink spills, pet spots, and dusty rugs.",
    image: "/images/services/carpet-cleaning.webp",
    serviceSlug: "carpet-cleaning",
    problem: "Carpets can hold stains, odors, allergens, and dust below the visible surface, especially in high-traffic rooms.",
    whyItMatters: "Ignoring stains can make them harder to remove and can make a clean room still feel old or dusty.",
    bestPlan: "Book carpet cleaning and share stain photos before the visit so the team can advise realistic expectations.",
    bullets: ["Do not scrub harshly before advice.", "Share stain age and cause if known.", "Keep the area ventilated after cleaning."],
    faqs: baseFaq("carpet-cleaning"),
  },
  {
    slug: "sofa-stain-cleaning-abu-dhabi",
    title: "Sofa Stain Cleaning in Abu Dhabi",
    eyebrow: "Upholstery support",
    description: "Guidance for sofa stains, fabric odor, dusty upholstery, family living rooms, and pre-guest sofa refreshes.",
    image: "/images/services/sofa-cleaning.webp",
    serviceSlug: "sofa-cleaning",
    problem: "Sofas collect spills, body oils, pet hair, food crumbs, dust, and marks from daily family use.",
    whyItMatters: "A sofa can look dull even when the room is clean because upholstery holds dust and stains differently from hard surfaces.",
    bestPlan: "Book sofa cleaning by seat count and send photos of fabric type, stains, and the full sofa before confirming scope.",
    bullets: ["Share number of seats.", "Mention fabric type if known.", "Ask about drying time before use."],
    faqs: baseFaq("sofa-cleaning"),
  },
  {
    slug: "bathroom-grout-cleaning-abu-dhabi",
    title: "Bathroom Grout Cleaning in Abu Dhabi",
    eyebrow: "Bathroom detail",
    description: "Cleaning guidance for dull grout, bathroom buildup, soap marks, corners, and areas that regular cleaning misses.",
    image: "/images/services/bathroom-cleaning.webp",
    serviceSlug: "deep-cleaning",
    problem: "Bathroom grout and corners can collect soap residue, moisture marks, dust, and discoloration over time.",
    whyItMatters: "Bathrooms may look unclean even after a normal wipe-down if grout and corners remain dull.",
    bestPlan: "Book deep cleaning for detailed bathroom attention and share photos of grout condition before the quote.",
    bullets: ["Send close-up grout photos.", "Mention number of bathrooms.", "Confirm whether glass and fixtures need extra focus."],
    faqs: baseFaq("deep-cleaning"),
  },
  {
    slug: "kitchen-grease-cleaning-abu-dhabi",
    title: "Kitchen Grease Cleaning in Abu Dhabi",
    eyebrow: "Kitchen detail",
    description: "Cleaning help for greasy counters, cooker areas, appliance exteriors, tiles, cabinets, and restaurant or home kitchens.",
    image: "/images/services/kitchen-cleaning.webp",
    serviceSlug: "deep-cleaning",
    problem: "Cooking grease builds up around stoves, tiles, hoods, cabinets, and nearby surfaces, especially with frequent use.",
    whyItMatters: "Grease attracts dust and can make kitchens feel sticky even after basic cleaning.",
    bestPlan: "Use deep cleaning for home kitchens or restaurant cleaning for commercial kitchens with hygiene-focused scope.",
    bullets: ["Share cooker and tile photos.", "Mention appliance interior needs separately.", "Confirm restaurant or home kitchen scope."],
    faqs: baseFaq("deep-cleaning"),
  },
  {
    slug: "window-dust-and-salt-cleaning-abu-dhabi",
    title: "Window Dust and Salt Cleaning in Abu Dhabi",
    eyebrow: "Glass care",
    description: "A window cleaning solution for dusty glass, balcony marks, salt air residue, frames, tracks, and streaks.",
    image: "/images/services/window-cleaning.webp",
    serviceSlug: "window-cleaning",
    problem: "Windows collect dust, fingerprints, water marks, salt air residue, frame dirt, and balcony exposure.",
    whyItMatters: "Dirty glass reduces brightness and makes even a clean room look unfinished.",
    bestPlan: "Book window cleaning and confirm whether interior, exterior, frames, and tracks are included in the requested scope.",
    bullets: ["Mention floor level and access.", "Confirm interior or exterior glass.", "Ask about frames and tracks."],
    faqs: baseFaq("window-cleaning"),
  },
  {
    slug: "move-in-dust-cleaning-abu-dhabi",
    title: "Move-In Dust Cleaning in Abu Dhabi",
    eyebrow: "Move-in support",
    description: "Cleaning support for empty apartments and villas before furniture, boxes, kitchen items, and family belongings arrive.",
    image: "/images/services/move-in-out-cleaning.webp",
    serviceSlug: "move-in-out-cleaning",
    problem: "Empty properties can hold dust in cabinets, floors, bathrooms, windowsills, wardrobes, and corners after maintenance or previous tenants.",
    whyItMatters: "Cleaning before unpacking is easier, faster, and more hygienic than cleaning around furniture and boxes later.",
    bestPlan: "Book move-in cleaning before furniture arrives and share handover timing, access, and property size.",
    bullets: ["Clean before unpacking.", "Check cabinets and wardrobes.", "Confirm utilities and water access."],
    faqs: baseFaq("move-in-out-cleaning"),
  },
  {
    slug: "post-renovation-dust-cleaning-abu-dhabi",
    title: "Post-Renovation Dust Cleaning in Abu Dhabi",
    eyebrow: "Renovation cleaning",
    description: "Cleaning support after maintenance, painting, repairs, renovation, drilling, sanding, and dusty handover work.",
    image: "/images/services/deep-cleaning.webp",
    serviceSlug: "deep-cleaning",
    problem: "Post-renovation dust can settle on floors, walls, cabinets, vents, windows, lights, and hidden edges.",
    whyItMatters: "Fine construction dust spreads easily and can return to surfaces even after a quick sweep.",
    bestPlan: "Book deep cleaning and send photos of dust level, room count, and renovation areas before confirming time.",
    bullets: ["Share renovation type.", "Mention paint or plaster dust.", "Plan a final check before moving items back."],
    faqs: baseFaq("deep-cleaning"),
  },
  {
    slug: "office-hygiene-cleaning-abu-dhabi",
    title: "Office Hygiene Cleaning in Abu Dhabi",
    eyebrow: "Office hygiene",
    description: "Cleaning support for office desks, shared surfaces, meeting rooms, pantry areas, restrooms, floors, and glass.",
    image: "/images/services/office-cleaning.webp",
    serviceSlug: "office-cleaning",
    problem: "Offices collect dust and germs on desks, handles, meeting tables, restrooms, pantry counters, and shared equipment.",
    whyItMatters: "A clean office supports staff comfort, client impressions, and daily workplace hygiene.",
    bestPlan: "Use recurring office cleaning with clear timing before opening, after closing, or during low-traffic hours.",
    bullets: ["List restricted rooms.", "Confirm access and security.", "Prioritize reception and restrooms."],
    faqs: baseFaq("office-cleaning"),
  },
  {
    slug: "restaurant-grease-cleaning-abu-dhabi",
    title: "Restaurant Grease Cleaning in Abu Dhabi",
    eyebrow: "Restaurant hygiene",
    description: "Cleaning support for restaurant kitchens, dining areas, floors, washrooms, grease zones, and high-use surfaces.",
    image: "/images/services/restaurant-cleaning.webp",
    serviceSlug: "restaurant-cleaning",
    problem: "Restaurant spaces deal with grease, food residue, foot traffic, washroom use, and daily hygiene expectations.",
    whyItMatters: "Food businesses need reliable cleaning routines to protect presentation, comfort, and hygiene standards.",
    bestPlan: "Book restaurant cleaning with clear kitchen, dining, floor, and washroom scope before the visit.",
    bullets: ["Confirm after-hours timing.", "Mention kitchen grease areas.", "List floors, washrooms, and dining spaces."],
    faqs: baseFaq("restaurant-cleaning"),
  },
  {
    slug: "showroom-presentation-cleaning-abu-dhabi",
    title: "Showroom Presentation Cleaning in Abu Dhabi",
    eyebrow: "Showroom care",
    description: "Cleaning support for showroom floors, glass, displays, counters, product zones, and visitor-facing spaces.",
    image: "/images/services/showroom-cleaning.webp",
    serviceSlug: "showroom-cleaning",
    problem: "Showrooms need clean glass, floors, counters, display areas, and visitor zones because small marks affect presentation.",
    whyItMatters: "A clean showroom helps products stand out and supports a stronger first impression for customers.",
    bestPlan: "Use showroom cleaning before opening, after closing, or before events and new product displays.",
    bullets: ["Prioritize glass and display zones.", "Confirm delicate product areas.", "Schedule around visitor hours."],
    faqs: baseFaq("showroom-cleaning"),
  },
  {
    slug: "balcony-dust-cleaning-abu-dhabi",
    title: "Balcony Dust Cleaning in Abu Dhabi",
    eyebrow: "Balcony dust",
    description: "Cleaning guidance for balconies, outdoor dust, glass doors, tracks, railings, and apartment exposure in Abu Dhabi.",
    image: "/images/services/window-cleaning.webp",
    serviceSlug: "window-cleaning",
    problem: "Balconies collect sand, dust, water marks, railing residue, glass marks, and dirt in sliding door tracks.",
    whyItMatters: "Balcony dust often gets pulled indoors and makes nearby rooms feel dusty again quickly.",
    bestPlan: "Combine home cleaning with window or balcony-focused attention where access and building rules allow it.",
    bullets: ["Mention balcony size.", "Confirm water access rules.", "Ask about sliding tracks and glass doors."],
    faqs: baseFaq("window-cleaning"),
  },
  {
    slug: "ac-dust-cleaning-abu-dhabi",
    title: "AC Dust Cleaning Support in Abu Dhabi",
    eyebrow: "AC dust support",
    description: "Cleaning support for homes where AC airflow moves dust onto shelves, bedrooms, vents, corners, and living room surfaces.",
    image: "/images/services/deep-cleaning.webp",
    serviceSlug: "deep-cleaning",
    problem: "AC airflow can move dust around rooms and make surfaces dusty soon after a basic clean.",
    whyItMatters: "Dust near vents, corners, shelves, and bedrooms can affect comfort and make cleaning feel temporary.",
    bestPlan: "Use regular home cleaning plus periodic deep cleaning for dust-prone corners, surfaces, and vent-adjacent areas.",
    bullets: ["Clean surfaces near vents.", "Prioritize bedrooms.", "Book deep cleaning for hidden dust buildup."],
    faqs: baseFaq("deep-cleaning"),
  },
  {
    slug: "weekly-maintenance-cleaning-abu-dhabi",
    title: "Weekly Maintenance Cleaning in Abu Dhabi",
    eyebrow: "Recurring cleaning",
    description: "A weekly cleaning plan for homes and apartments that need consistent dust control, bathroom care, kitchen upkeep, and floor cleaning.",
    image: "/images/services/home-cleaning.webp",
    serviceSlug: "home-cleaning",
    problem: "Homes can feel dusty again within a week because of AC airflow, outdoor sand, family traffic, and daily use.",
    whyItMatters: "Weekly cleaning prevents buildup and reduces the need for urgent heavy cleaning before guests or weekends.",
    bestPlan: "Book weekly home cleaning and add deep cleaning seasonally or when hidden areas need attention.",
    bullets: ["Set a fixed weekly day.", "Keep priority rooms consistent.", "Add deep cleaning every few months."],
    faqs: baseFaq("home-cleaning"),
  },
  {
    slug: "guest-ready-cleaning-abu-dhabi",
    title: "Guest-Ready Cleaning in Abu Dhabi",
    eyebrow: "Before guests",
    description: "Cleaning support before family visits, events, gatherings, guests, short stays, and special occasions.",
    image: "/images/services/apartment-cleaning.webp",
    serviceSlug: "apartment-cleaning",
    problem: "Before guests arrive, the most visible areas need fast attention: living rooms, bathrooms, kitchen surfaces, floors, glass, and sofa areas.",
    whyItMatters: "Guest-ready cleaning improves comfort and presentation without necessarily needing a full deep clean every time.",
    bestPlan: "Book apartment or home cleaning, then add sofa, carpet, or window cleaning if visible areas need extra care.",
    bullets: ["Prioritize bathrooms and living room.", "Check sofa and carpet condition.", "Book early before weekends or holidays."],
    faqs: baseFaq("apartment-cleaning"),
  },
  {
    slug: "tenant-handover-cleaning-abu-dhabi",
    title: "Tenant Handover Cleaning in Abu Dhabi",
    eyebrow: "Handover cleaning",
    description: "Cleaning support before tenancy handover, landlord inspection, move-out, move-in, or property listing.",
    image: "/images/services/move-in-out-cleaning.webp",
    serviceSlug: "move-in-out-cleaning",
    problem: "Handover properties often need bathrooms, kitchens, floors, cabinets, windowsills, and empty-room dust handled before inspection.",
    whyItMatters: "A clean property helps handover feel smoother and reduces last-minute complaints about visible dirt.",
    bestPlan: "Book move-out cleaning after furniture removal and before final inspection or key handover.",
    bullets: ["Clean after items are removed.", "Share inspection deadline.", "Confirm cabinets, bathrooms, and floors."],
    faqs: baseFaq("move-in-out-cleaning"),
  },
  {
    slug: "family-home-cleaning-abu-dhabi",
    title: "Family Home Cleaning in Abu Dhabi",
    eyebrow: "Family homes",
    description: "Cleaning support for busy families with bedrooms, bathrooms, kitchens, toys, guest areas, spills, and weekly dust.",
    image: "/images/services/home-cleaning.webp",
    serviceSlug: "home-cleaning",
    problem: "Family homes build up dust, kitchen use, bathroom marks, floor mess, toys, and daily clutter faster than low-traffic homes.",
    whyItMatters: "A consistent cleaning routine keeps family spaces healthier, calmer, and easier to maintain.",
    bestPlan: "Use weekly home cleaning, then add sofa, carpet, or deep cleaning based on family traffic and stains.",
    bullets: ["Prioritize bathrooms and kitchen.", "Share rooms used most by children.", "Add fabric cleaning when sofas or rugs hold stains."],
    faqs: baseFaq("home-cleaning"),
  },
  {
    slug: "small-apartment-cleaning-abu-dhabi",
    title: "Small Apartment Cleaning in Abu Dhabi",
    eyebrow: "Apartment cleaning",
    description: "Cleaning plans for studios, 1BHK, and compact apartments where dust, bathroom use, kitchen surfaces, and floors need regular attention.",
    image: "/images/services/apartment-cleaning.webp",
    serviceSlug: "apartment-cleaning",
    problem: "Small apartments can feel messy quickly because kitchens, living areas, bedrooms, and storage are close together.",
    whyItMatters: "A compact home feels cleaner and more comfortable when dust, floors, bathrooms, and surfaces are maintained regularly.",
    bestPlan: "Book apartment cleaning for regular upkeep and add deep cleaning when cabinets, corners, or appliances need detail.",
    bullets: ["Share apartment size.", "Mention studio, 1BHK, or 2BHK.", "Prioritize kitchen, bathroom, and floors."],
    faqs: baseFaq("apartment-cleaning"),
  },
];

export function getCleaningSolution(slug: string) {
  return cleaningSolutions.find((solution) => solution.slug === slug);
}
